# Shared definitions for blackmatter-secrets.
#
# Backend-agnostic secret/template submodule types and helpers.
{ lib }:

rec {
  # ── Backend types ──────────────────────────────────────────────────
  backendType = lib.types.enum [ "sops" "akeyless" ];

  # ── Secret submodule (backend-agnostic) ────────────────────────────
  secretSubmodule = lib.types.submodule {
    options = {
      path = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Target file path (empty = auto-generated by backend).";
      };
      mode = lib.mkOption {
        type = lib.types.str;
        default = "0400";
        description = "File permission mode (octal).";
      };
      owner = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "File owner (empty = current user).";
      };
      group = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "File group (empty = current group).";
      };
      restartUnits = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "Systemd units to restart when this secret changes.";
      };
      reloadUnits = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "Systemd units to reload when this secret changes.";
      };
    };
  };

  # ── Template submodule (backend-agnostic) ──────────────────────────
  templateSubmodule = lib.types.submodule {
    options = {
      path = lib.mkOption {
        type = lib.types.str;
        description = "Target file path for rendered template.";
      };
      content = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Template content (use secrets.placeholder for substitution).";
      };
      file = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Template file (read at eval time, takes precedence over content).";
      };
      mode = lib.mkOption {
        type = lib.types.str;
        default = "0400";
      };
      owner = lib.mkOption { type = lib.types.str; default = ""; };
      group = lib.mkOption { type = lib.types.str; default = ""; };
    };
  };
}
